### ISSUE TITLE
appendComputation method for Computation inlining

### ISSUE THREAD

**Issue by riftEmber** [BoiseState-AdaptLab/IEGenLib#19]
Development is on the `append-computation` branch, which is branched off of `main`.

List of concerns, using the example of a Computation `B` being appended to (inserted inside) a computation `A`.
- [ ] Appending iterator tuples to each other; if B's tuple is `[i]` and A's is `[i, j]`, after appending the statements that belonged to B should have the tuple `[i,j,k]` with `k` corresponding to B's old `i`. The 'new' iterator variable should be generated a name. Any references to the old `i` in B will now have to point to tuple variable index 2 instead of 0.
- [ ] Execution schedule of the newly added statements must 'fall under' the current execution ordering tuple.
- [ ] Symbolic constants used inside B should be renamed (prefixed or suffixed), whether there is a name shadowing issue or not for clarity.
- [ ] Copying over data spaces accessed. Need to resolve naming conflicts?
- more that I'm overlooking...

Questions:
- What is the best format for the required iterspace/execution schedule information to be passed into appendComputation?
- Do changes in variable names made to B need to be reflected in statement source code string?
- Should data space names that are the same be considered the same data space, or do the names need to be changed?
- Is appendComputation the best name for this, it seems to be more inserted than appended with this plan.

**Comment by cathieO** [comment]
Anna, I think we aren't on the same page with this yet. I propose that we start with an example.
The most simple example is one where we will be adding a computation to the end of our current computation. In that case, the caller needs to somehow know that last tuple that was used in a scheduling function... let's assume that S15 was just created and added to a computation and its scheduling function is [4,i,6,j,2]. Further our new computation B has 3 statements in it (R0,R1,R2) and they have some control flow. AppendComputation will need to go through each statement in B clone it, and insert it into A. Each of R0-R2 will have their own scheduling function. Let's say that they are [c1,c2,c3], [c4,c5,c6],[c7,c8,c9]. Now, when we insert each one we will need to add 4 to the first tuple. c1+4, c4+4, and c7+4. We also need to pad the scheduling functions to have extra 0's so that they are all the same length. We would like to continue adding statements at this point, but don't know what our next scheduling function should be. We need appendComputation to return [c7+4,c8,c9,0,0]. This is the most simple case - it assumes that the depth of the addition to the schedule is 0. However, the depth _might_ be larger. Let's get this case working first and then we can move on to the harder cases.

**Comment by riftEmber** [comment]
That sounds like a good starting point. I'm not sure how we'd know that we need to add to the first item in the tuple; that seems like more context that would need to be passed into the function. Specifically, if the function call being inlined occurs within one or more loops, I think we'd want to prepend the previous scheduling function tuple. In the above case, if the Computation being inlined is being nested within both the `i` and `j` loops, I think the resulting execution schedules would be [4,i,6,j,2+c1,c2,c3], [4,i,6,j,2+c4,c5,c6], [4,i,6,j,2+c7,c8,c9]. However, if the Computation (function call being inlined) occurs after the `i` and `j` loops, it would be as you wrote above. Is that correct?

**Comment by cathieO** [comment]
Yes, you've got it right

**Comment by cathieO** [comment]
I'd prefer the first iteration of this assume depth=0.  We can then add the logic and a parameter for depth later. I suspect there will be other issues as well as we go. I anticipate needing to create new read and write relations (for the function that we are inlining).

**Comment by riftEmber** [comment]
The depth thing makes sense. What would we need to create new read and write functions for though? Doesn't the inlined Computation already have its own reads and writes taken care of?

**Comment by riftEmber** [comment]
Ok, appendComputation that can adjust execution schedules at depth 0 is done in d422636be8f61c05d84a1e35863cc39736c15011, and made more readable in db4295ce695648943ceb55c5ab27eed8238e1540. Next step is probably enabling depths other than 0, which will require prepending to the execution schedule, renaming tuple variables, and offsetting tuple variable terms' locations.

**Comment by cathieO** [comment]
Task for @rvishnkr 

- [ ] Update unit tests to not use a string in the expected value.

**Comment by riftEmber** [comment]
Closing this issue in favor of the new epic
