### ISSUE TITLE
Memory management for the computation

### ISSUE THREAD

**Issue by rvishnkr** [BoiseState-AdaptLab/IEGenLib#30]
Allocating memory for a statement on the stack and adding it to a computation is causing undefined behavior.

**Comment by riftEmber** [comment]
#32

**Comment by riftEmber** [comment]
Should be fixed by #32 (which is now merged), it is now considered incorrect to put Stmts or Computations on the stack like all other major iegenlib data structures. As far as I know there should be no more instances of Stmts or Computations on the stack left in the code currently, but if you find one it should be changed. And let me know if there are any new memory-management issues that come up with heap pointers.
